### ISSUE TITLE
[Moon2] Add option for additional labels on the Service

### ISSUE THREAD

**Issue by dani-CO-CN** [aerokube/charts#131]
I want to add a Prometheus ServiceMonitor, but there are no labels on the service to select for and i can't add additional labels through the [helm chart](https://github.com/aerokube/charts/blob/master/moon2/templates/service.yaml#L4-L6).

**Comment by dani-CO-CN** [comment]
As described in the [docs](https://aerokube.com/moon/latest/#monitoring), i use the prometheus operator and for automatic target discovery. For the operator to discover the targets i use the [prometheus service monitor custom resource](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#related-resources) . But to get the service discovery i need to select the service based on labels and i don't have any :smile: 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-moon-browser-metrics
spec:
  selector:
    matchLabels:
      #  no labels on the service therefore i can't select it
  - port: moon
```
I could also use PodMonitor, but the port on the deployment pods are not named and i have to hardcode the port.
