### ISSUE TITLE
Can't upgrade to 2.5.0

### ISSUE THREAD

**Issue by AmitBaranes** [aerokube/charts#200]
When i try to upgrade helm to latest version i face this issue:

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Config.spec.containers): unknown field "proxy" in com.aerokube.moon.v1.Config.spec.containers`

values.yaml:

```
ingress:
  enabled: true
  host: moon.xxx.xxx
  ingressClassName: nginx
service:
  type: ClusterIP
deployment:
  replicas: 2
configs:
  default:
    storage:
      endpoint: https://s3.eu-west-1.amazonaws.com
      bucket: moon
      accessKey: dummy
      secretKey: dummy
license: dummy
browsers:
  default:
    selenium:
      chrome:
        repository: quay.io/browser/google-chrome-stable
        default: 112.0.5615.165-5
```

Any ideas?
