### ISSUE TITLE
How to set annotation for the browser pod in Moon2?

### ISSUE THREAD

**Issue by disparo13** [aerokube/charts#240]
Hi! I'm trying to set the pod annotation via the moon2 helm chart, but there's nothing in the documentation about that, and my trying to set it like
```
  configs:
    default:
      containers:
        browser:
          annotations:
            karpenter.sh/do-not-disrupt: "true"
```
returns 
`W1227 17:34:58.050243   28191 warnings.go:70] unknown field "spec.containers.browser.annotations"`
and nothing works.
