### ISSUE TITLE
Empty space in htpasswd if helm chart is deployed via rancher

### ISSUE THREAD

**Issue by benzman81** [aerokube/charts#32]
Hi,
we use rancher as a cluster manager. If I set the following yaml as values, then the entry in the user htpasswd secrect contains an empty space. This way, the login wont work. Removing the empty space makes it work again.

Here is the yaml:
```
moon:
  htpasswd: |
    test:$apr1$.dZyHlKN$jdoZkin/kPviFNArx/cVL1
  service:
    type: NodePort
```
If I remove the service configuration, than there will be no empty space.
