### ISSUE TITLE
No XSession started

### ISSUE THREAD

**Issue by boskiv** [aerokube/charts#6]
Can't connect with VNC via UI
values.yaml
```
---
moon:
  ingress:
    host: moon-app.xxxxxx.io
  s3:
    endpoint: http://minio.xxxxx.io
    bucketName: moon
    accessKey: "moondata"
    secretKey: "moondata"
```

![x11](https://user-images.githubusercontent.com/1939783/88984494-61240f00-d293-11ea-8441-49fe69f0b209.png)
