### ISSUE TITLE
Add tolerations for browser pods

### ISSUE THREAD

**Issue by dani-CO-CN** [aerokube/charts#65]
In my use case all nodes have taints, therefore the browser pods stay pending

**Comment by vania-pooh** [comment]
Right now it's possible to add tolerations to `quota` section manually in `values.yaml` (https://github.com/aerokube/charts/blob/master/moon/values.yaml#L366):

```
  quota:
    browsers:
      safari:
        default: "14.0"
        versions:
          "14.0":
            image: quay.io/browsers/safari:14.0
            port: "4444"
            path: "/"
            tolerations:
              - key: "key1",
                 operator": "Exists"
                 value: "value1"
                 effect: "NoExecute"
                 tolerationSeconds: 3600
```

In fact YAML under `quota` key is being converted to JSON so the following documentation is applicable: https://aerokube.com/moon/latest/#tolerations
